export const PAKISTAN_CITIES = [
    // Punjab
    "Lahore",
    "Rawalpindi",
    "Faisalabad",
    "Multan",
    "Gujranwala",
    "Sialkot",
    "Bahawalpur",
    "Sargodha",
    "Sheikhupura",
    "Rahim Yar Khan",
    "Jhelum",
    "Kasur",
    "Gujrat",
    "Okara",
    "Dera Ghazi Khan",
    "Vehari",
    "Mianwali",
    "Chiniot",
    "Bhakkar",
    "Lodhran",
    "Khanewal",
    "Toba Tek Singh",
    "Narowal",
    "Attock",
    "Muzaffargarh",
    "Pakpattan",
    "Rajanpur",
    "Hafizabad",
    "Mandi Bahauddin",
    "Sahiwal",
    "Jhang",
    "Layyah",
    "Nankana Sahib",
    "Khushab",
    "Bahawalnagar",

    // Sindh
    "Karachi",
    "Hyderabad",
    "Sukkur",
    "Larkana",
    "Nawabshah (Shaheed Benazirabad)",
    "Mirpur Khas",
    "Jacobabad",
    "Khairpur",
    "Shikarpur",
    "Dadu",
    "Ghotki",
    "Thatta",
    "Badin",
    "Tando Adam",
    "Tando Allahyar",
    "Umerkot",
    "Matiari",

    // Khyber Pakhtunkhwa (KPK)
    "Peshawar",
    "Abbottabad",
    "Mardan",
    "Swat (Mingora)",
    "Bannu",
    "Kohat",
    "Dera Ismail Khan",
    "Charsadda",
    "Mansehra",
    "Haripur",
    "Nowshera",
    "Swabi",
    "Hangu",
    "Lakki Marwat",
    "Tank",
    "Batkhela",

    // Balochistan
    "Quetta",
    "Gwadar",
    "Turbat",
    "Khuzdar",
    "Sibi",
    "Zhob",
    "Loralai",
    "Chaman",
    "Dera Murad Jamali",
    "Pishin",
    "Hub",
    "Kalat",
    "Ziarat",

    // Azad Jammu & Kashmir (AJK)
    "Muzaffarabad",
    "Mirpur",
    "Rawalakot",
    "Bagh",
    "Kotli",
    "Bhimber",

    // Gilgit-Baltistan
    "Gilgit",
    "Skardu",
    "Hunza",
    "Gahkuch",
    "Chilas",
    "Khaplu",

    // Islamabad Capital Territory
    "Islamabad"
];
